customhost = "employee.cwuynnhawpb9.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "cheongpeizi-employee"
customregion = "us-east-1"
